name: Spring Boot CI/CD Pipeline

on: 
  push:
    branches:
      - main   

jobs:
  test:
    name: Run Tests with JaCoCo 
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio 
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'

      #paso 3: Cache de dependencias maven
      - name: Cache Maven Dependencies 
        uses: actions/cache@v3
        with: 
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Paso 4: construir el proyecto y ejecutar test 
      - name: Build and test
        run: mvn clean verify

      # Paso 5: Construir la imagen de Docker
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with: 
          name: jacoco-Report
          path: target/site/jacoco